/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.Organization.BankEmployeeOrganization;
import Business.Organization.Organization;
import Business.UserAccount.LoginDetails;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import userinterface.SignUp.SignUp;

/**
 *
 * @author Sumeet
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private static EcoSystem system;
    public static DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    private UserAccount loginAccount = null;

    public MainJFrame() {
        initComponents();
        addBackground();
        closeJButton.setVisible(false);
        this.setAlwaysOnTop(true);
        this.setSize(1150, 630);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Bank Application");

        system = dB4OUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        userNameJTextField = new javax.swing.JTextField();
        passwordJTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        signUpJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InfojLabel6 = new javax.swing.JLabel();
        closeJButton = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(160);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginJButton.setBackground(new java.awt.Color(255, 255, 255));
        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 274, 130, -1));
        jPanel1.add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 152, 130, 29));
        jPanel1.add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 219, 130, 29));

        jLabel1.setText("User Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 123, -1, -1));

        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 190, -1, -1));
        jPanel1.add(loginJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 346, -1, -1));

        logoutJButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutJButton.setText("Logout");
        logoutJButton.setEnabled(false);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 312, 130, -1));

        signUpJButton.setBackground(new java.awt.Color(255, 255, 255));
        signUpJButton.setText("Sign Up");
        signUpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(signUpJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 419, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sumeet\\Desktop\\Assignments\\AED Assignments\\Final\\bank-icon.png")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 466, 136, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/credit-card-icon.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 37, 75, 48));

        InfojLabel6.setText("If New Customers");
        InfojLabel6.setEnabled(false);
        jPanel1.add(InfojLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 130, -1));

        closeJButton.setBackground(new java.awt.Color(255, 255, 255));
        closeJButton.setText("Close");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(closeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 130, -1));

        jSplitPane1.setLeftComponent(jPanel1);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpJButtonActionPerformed

        // Assumption: Expects a BankPersonOrganisation to exist in the system
        EnterpriseDirectory enterpriseDirectory = system.getNetworkList().get(0).getEnterpriseDirectory();
        Enterprise enterprise = system.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().get(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof BankEmployeeOrganization) {
                SignUp signUpJPanel = new SignUp(container, null, (BankEmployeeOrganization) organization);
                container.add("signUpPage", signUpJPanel);

                CardLayout layout = (CardLayout) container.getLayout();
                layout.next(container);
                break;
            }
        }

        disableAllFeatures();
        signUpJButton.setVisible(false);
        closeJButton.setVisible(true);
    }//GEN-LAST:event_signUpJButtonActionPerformed

    private void disableAllFeatures() {
        loginJButton.setEnabled(false);
        logoutJButton.setEnabled(false);
        signUpJButton.setEnabled(false);
        userNameJTextField.setEnabled(false);
        passwordJTextField.setEnabled(false);
        InfojLabel6.setVisible(false);
    }

    private void enableAllFeatures() {
        loginJButton.setEnabled(true);
        logoutJButton.setEnabled(true);
        signUpJButton.setEnabled(true);
        userNameJTextField.setEnabled(true);
        passwordJTextField.setEnabled(true);
        InfojLabel6.setVisible(true);
    }

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        userNameJTextField.setText("");
        passwordJTextField.setText("");

        if (loginAccount != null) {
            LoginDetails latestLoginDetails = loginAccount.getLatestLoginDetails();
            latestLoginDetails.updateLogoutTime();
        }

        enableAllFeatures();
        logoutJButton.setEnabled(false);
        addBackground();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    public static void saveData() {
        dB4OUtil.storeSystem(system);
    }

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // Get user name
        String userName = userNameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordJTextField.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system user account directory if you have the user
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);

        if (userAccount != null) {
            loadUserPage(userAccount, null, null);
            return;
        }

        for (Network network : system.getNetworkList()) {
            //Step 2-a: Check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                if (null != userAccount) {
                    loadUserPage(userAccount, null, enterprise);
                    return;
                }

                //Step3: Check against each organization inside that enterprise
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                    if (null != userAccount) {
                        loadUserPage(userAccount, organization, enterprise);
                        return;
                    }
                }
            }
        }
        
        JOptionPane.showMessageDialog(this, "Invalid Username and Password", "Try again", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        addBackground();
        signUpJButton.setVisible(true);
        closeJButton.setVisible(false);
        enableAllFeatures();

    }//GEN-LAST:event_closeJButtonActionPerformed

    private void loadUserPage(UserAccount userAccount, Organization inOrganization, Enterprise inEnterprise) {
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, system));
        layout.next(container);
        userAccount.addLoginDetails();
        this.loginAccount = userAccount;
        disableAllFeatures();
        logoutJButton.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfojLabel6;
    private javax.swing.JButton closeJButton;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwordJTextField;
    private javax.swing.JButton signUpJButton;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
    private JLabel labelBackground = new JLabel();

    private void addBackground() {
        container.removeAll();
        labelBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sumeet\\Desktop\\Assignments\\AED Assignments\\Final\\9.jpg")); // NOI18N
        container.add(labelBackground, "card2");
    }
}
