/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CoreBankingTeamRole;

import EDU.purdue.cs.bloat.decorate.Main;
import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class NewUserDocumentJPanel extends javax.swing.JFrame {

    JLabel documentHolder;
    BufferedImage image;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public NewUserDocumentJPanel(String filePath) {
        initComponents();
        documentHolder = new JLabel();
        add(documentHolder);
        final ImageIcon imageIcon = new javax.swing.ImageIcon(filePath);
        documentHolder.setIcon(imageIcon);
        documentHolder.setSize(imageIcon.getIconWidth(), imageIcon.getIconHeight());
    }

    public void loadPage(String title) {
        setSize((int) documentHolder.getSize().getWidth() + 25, (int) documentHolder.getSize().getHeight() + 65);
        this.setLocationRelativeTo(null);
        this.setTitle(title);
        this.setVisible(true);
        this.setAlwaysOnTop(true);
        this.setAutoRequestFocus(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentPane().setLayout(new java.awt.FlowLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
